-- 코드를 입력하세요
SELECT FLAVOR FROM (SELECT FH.FLAVOR,TOTAL_ORDER,INGREDIENT_TYPE FROM FIRST_HALF AS FH
INNER JOIN 
    (SELECT INGREDIENT_TYPE,FLAVOR FROM ICECREAM_INFO) AS ICE
ON
    FH.FLAVOR=ICE.FLAVOR
WHERE TOTAL_ORDER>=3000) AS ANS
WHERE INGREDIENT_TYPE='fruit_based'
ORDER BY TOTAL_ORDER DESC;
