-- 코드를 입력하세요

SELECT * FROM (
SELECT  CAR_ID,ROUND(AVG(DURATION+1),1) AS AVERAGE_DURATION FROM (SELECT CAR_ID, DATEDIFF(END_DATE,START_DATE) AS DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS DURH
GROUP BY CAR_ID) AS ANS
WHERE AVERAGE_DURATION>=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;