-- 코드를 입력하세요
SELECT 
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,SUM(B.PRICE*SA.SALES) AS TOTAL_SALES
FROM 
    BOOK AS B 
INNER JOIN AUTHOR AS A 
    ON B.AUTHOR_ID = A.AUTHOR_ID 
INNER JOIN 
    BOOK_SALES AS SA ON B.BOOK_ID=SA.BOOK_ID
WHERE 
    SA.SALES_DATE LIKE '%2022-01%'
GROUP BY 
    B.AUTHOR_ID,B.CATEGORY
ORDER BY
    A.AUTHOR_ID ,
    B.CATEGORY DESC;