-- 코드를 입력하세요
-- SELECT HISTORY_ID,CAR_ID,START_DATE,END_DATE,
SELECT  HISTORY_ID,CAR_ID,DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
-- SELECT HISTORY_ID,CAR_ID,START_DATE,END_DATE,
    CASE
        WHEN DURATION >=30 THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM(SELECT *, DATEDIFF(END_DATE,START_DATE)+1 AS DURATION FROM (SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(start_date,'%Y-%m-%d') between '2022-09-01' and '2022-09-30') AS DUR) AS ANS
ORDER BY HISTORY_ID DESC;