-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE FROM BOOK 
WHERE 
(DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') between '2021-01-01' and '2021-12-31') AND
CATEGORY='인문'
ORDER BY PUBLISHED_DATE;