-- 코드를 입력하세요
SELECT INGREDIENT_TYPE,SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM
(SELECT INGREDIENT_TYPE,TOTAL_ORDER FROM FIRST_HALF 
INNER JOIN
    (SELECT FLAVOR,INGREDIENT_TYPE FROM ICECREAM_INFO ) AS ICE
ON
    FIRST_HALF.FLAVOR=ICE.FLAVOR) AS ING_ORDER
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER;