SELECT
    AP.APNT_NO,P.PT_NAME, AP.PT_NO,AP.MCDP_CD,D.DR_NAME,AP.APNT_YMD
FROM 
    APPOINTMENT AS AP 
JOIN 
    PATIENT AS P 
JOIN
    DOCTOR AS D
ON 
    P.PT_NO = AP.PT_NO AND D.DR_ID = AP.MDDR_ID
WHERE 
    AP.MCDP_CD = 'CS' AND AP.APNT_YMD LIKE '%22-04-13%' AND AP.APNT_CNCL_YN = 'N'
GROUP BY 
    PT_NAME 
ORDER BY 
    AP.APNT_YMD ;