-- 코드를 입력하세요
SELECT BOOK_ID,AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE FROM BOOK AS BO
INNER JOIN
    (SELECT AUTHOR_NAME,AUTHOR_ID FROM AUTHOR) AS AU 
ON
    BO.AUTHOR_ID=AU.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE
;